name: Build (Windows)

on: [ push ]

jobs:
  build:
    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v2
      
      - name: Install build deps
        run: |
          choco install mingw golang rust dart-sdk haskell-dev nim swiftforwindows -y
        
      - name: Build
        run: |
          g++ -c c++/HelloWorld.cpp && g++ -o HelloWorld-cpp-windows-x64.exe HelloWorld.o
          gcc c/HelloWorld.c -o HelloWorld-c-windows-x64.exe
          go build golang/helloWorld.go && mv helloWorld helloWorld-go-windows-x64.exe
          rustc rust/helloWorld.rs -o helloWorld-rust-windows-x64.exe
          dart compile exe dart/hello_world.dart -o hello_world-dart-windows-x64.exe
          ghc haskell/helloworld.hs -o helloworld-haskell-windows-x64.exe
          nim compile nim/helloWorld.nim && mv nim/helloWorld helloWorld-nim-windows-x64.exe
          swiftc swift/helloWorld.swift -o helloWorld-swift-windows-x64.exe
       
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: Built
          path: *.exe
          
