name: Build (Linux)

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      
      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang gcc g++ nasm golang lua5.3 nim rustc
        
      - name: Build
        run: |
          g++ -c c++/HelloWorld.cpp && g++ -o HelloWorld-cpp-x64 HelloWorld.o
          gcc c/HelloWorld.c -o HelloWorld-c-x64
          go build golang/helloWorld.go && mv helloWorld helloWorld-go-x64
          luac lua/helloWorld.lua && mv luac.out helloWorld-lua-x64
          rustc rust/helloWorld.rs -o helloWorld-rust-x64
          nasm -f elf64 -o helloworld.o x86_64\ assembly/helloworld.S && ld -o helloworld-assembly-linux-x64 helloworld.o
          rm *.o
       
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: Built
          path: |
            hello*
            Hello*
          
