name: Build Docker Image

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build Docker Image
        run: docker build --no-cache -f Dockerfile -t hellobuild .
      
      - name: Get size of Docker Image
        run: docker system df -v
